/**
 *
 *  @file PdfWriterTests.cpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.
 *  All rights reserved.
 *  https://github.com/rixcpp/pdf
 *
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 *  Rix
 *
 */

#include <rix/pdf/document/Document.hpp>
#include <rix/pdf/writer/PdfWriter.hpp>

#include <cassert>
#include <string>

int main()
{
  using namespace rixlib::pdf;
  using namespace rixlib::pdf::writer;

  PdfWriter writer;

  Document empty;

  auto empty_pdf = writer.write(empty);

  assert(empty_pdf.ok());
  assert(!empty_pdf.value().empty());
  assert(empty_pdf.value().find("%PDF-1.4") != std::string::npos);
  assert(empty_pdf.value().find("/Type /Catalog") != std::string::npos);
  assert(empty_pdf.value().find("/Type /Pages") != std::string::npos);
  assert(empty_pdf.value().find("/Count 1") != std::string::npos);
  assert(empty_pdf.value().find("xref") != std::string::npos);
  assert(empty_pdf.value().find("%%EOF") != std::string::npos);

  Document doc;

  doc.set_title("Rix PDF Test")
      .set_author("Gaspard Kirira")
      .set_subject("Writer test");

  auto &page = doc.add_page();

  page.heading(
      page.x_left(),
      page.y_top(),
      "Rix PDF",
      1);

  page.text(
      page.x_left(),
      page.y_top() - 50.0F,
      "Hello from rix/pdf");

  page.paragraph(
      page.x_left(),
      page.y_top() - 80.0F,
      page.content_width(),
      "This document is generated by the rix/pdf writer.",
      Align::Left);

  Table table;
  table.set_column_widths({160.0F, 160.0F});
  table.add_header({"Name", "Project"});
  table.add_row({"Ada", "Rix"});
  table.add_row({"Gaspard", "Vix.cpp"});

  page.table(
      page.x_left(),
      page.y_top() - 160.0F,
      table);

  auto pdf = writer.write(doc);

  assert(pdf.ok());

  const std::string &data = pdf.value();

  assert(data.find("%PDF-1.4") != std::string::npos);
  assert(data.find("/Title (Rix PDF Test)") != std::string::npos);
  assert(data.find("/Author (Gaspard Kirira)") != std::string::npos);
  assert(data.find("/Subject (Writer test)") != std::string::npos);
  assert(data.find("/Creator (rix/pdf)") != std::string::npos);
  assert(data.find("/BaseFont /Helvetica") != std::string::npos);
  assert(data.find("/BaseFont /Helvetica-Bold") != std::string::npos);
  assert(data.find("(Hello from rix/pdf) Tj") != std::string::npos);
  assert(data.find("(Ada) Tj") != std::string::npos);
  assert(data.find("xref") != std::string::npos);
  assert(data.find("trailer") != std::string::npos);
  assert(data.find("startxref") != std::string::npos);
  assert(data.find("%%EOF") != std::string::npos);

  auto bad_save = writer.save(doc, "");

  assert(bad_save.failed());
  assert(bad_save.error().is(PdfErrorCode::InvalidInput));

  return 0;
}
